# Developed by Eng Mouaz M AlShahmeh
name: meta_seo
description: Meta SEO is package for adding meta data for html document in head tag which meta tags or meta data make search engine optimization for web apps.
version: 3.0.12
repository: https://github.com/Eng-Mouaz-M-AlShahmeh/meta_seo
issue_tracker: https://github.com/Eng-Mouaz-M-AlShahmeh/meta_seo/issues
topics: [meta-seo, seo]
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  html_character_entities:
  web:
